sudo: false
language: python

git:
  depth: 4

env:
  - LUA_RUNTIME="luajit"
    LUA_VERSION="2.0.3"
  - LUA_RUNTIME="luajit"
    LUA_VERSION="2.1"

before_install:
  - pip install hererocks
  - hererocks lua_installations/$LUA_RUNTIME$LUA_VERSION/ --luarocks ^ --$LUA_RUNTIME $LUA_VERSION
  - export PATH=$PATH:$PWD/lua_installations/$LUA_RUNTIME$LUA_VERSION/bin

install:
  - luarocks make

before_script:
  - luarocks install busted
  - busted --version

script:
  - busted --output=TAP

cache:
  directories:
    - $PWD/lua_installation

notifications:
  recipients:
    - arne@twobeer.de
  email:
    on_failure: always
